[tool.black]
line-length = 79

[tool.coverage.run]
parallel = true
branch = true
source = ["{{cookiecutter.package}}"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
